### ISSUE TITLE
HTTP-based notification images not displayed after being routed through caching service

### ISSUE THREAD

**Issue by mitchellkrogza** [OneSignal/OneSignal-Website-SDK#109] opened 2016-08-15 16:15 UTC
In the settings of OneSignal you ask for a url on my site where my notification image resides. Why then are the images being proxied through https://images.weserv.nl/ and then of course failing miserably as you can see below. Why not just pull the image directly from my site?

A lot of SSL sites have a content security policy in place which will normally prevents an external  site that is not specified in the CSP from calling any resources from the site directly. This however does not even show up in my Content Security Log so something is not right here with the way tou are calling these images and it makes all notifications look poorly coded because none of them have any images whatsoever.

```
Error 404: Server could parse the ?url= that you were looking for, error it got: Empty reply from server

Also, if possible, please replace any occurences of of + in the ?url= with %2B (see + bug)
```

**Comment by jasonpang** [comment] 2016-08-15 17:51
Hello,

We're really sorry about this; we've coded a fix here and will deploy this very soon (https://github.com/OneSignal/OneSignal-Website-SDK/commit/c9ed6f6cde8431a95e9d5a2f16bec56024330de7).

**Comment by mitchellkrogza** [comment] 2016-08-16 07:43
Hi Jason, awesome so glad you are attending to this. Looking forward to the next update.

KR
Mitchell

**Comment by jasonpang** [comment] 2016-08-18 22:33
If an HTTPS image resource is used, it should load properly as it will load the specified resource without being routed through any 3rd party service (as it was originally). Because this has always worked, we don't expect any issues. (This update has already been released as of a couple days ago).

For HTTP image resources, some users are unable to provide HTTPS image resources (e.g. WordPress allows attaching a "featured image" to each post and WordPress services the image from the site itself, so if the site is HTTP, so is the featured image), so we have to continue proxying the image. We're still getting reports of users not being able to see any images, and we haven't yet determined the root cause for this.

**Comment by mitchellkrogza** [comment] 2016-08-19 07:32
Thanks Jason, you and I already caught on on email about this. Your fix to [serviceworker.js](https://github.com/OneSignal/OneSignal-Website-SDK/commit/c9ed6f6cde8431a95e9d5a2f16bec56024330de7)  has fixed this perfectly and now notifications icons, including post notification icons are working 100% across 9 sites now. I think your biggest issue is trying to handle https and http sites all in one. With things like Let's Encrypt around I can't see why people are not just turning to SSL and moving ahead. It certainly makes things easier.

**Comment by jasonpang** [comment] 2016-08-20 02:43
@mitchellkrogza Thanks for the feedback! Glad to hear the HTTPS resources are now loading fine again. 

For HTTP sites, we are working on a couple of things and trying to get the HTTP resources working again as well.

**Comment by mitchellkrogza** [comment] 2016-08-20 08:56
@jasonpang  I am quite sure you will figure it out soon, I have no doubt. Must say that since the first time I ever configured OneSignal on my first site until today, you guys have streamlined the process so much. It takes me a little over 5 minutes to configure a new site in OneSignal now including creating all my different sized icons, it's an utter breeze. Oh ... not for this thread but please check your first part of an app creation "Web Site Push / Chrome & Firefox" where it allows you to set your own notification icon. That setting screen says icon should be 192x192 but your older documentation says 80x80 and I make mine all 80x80 and they work fine. Not sure if the 192x192 is intentional or not? You guys keep up the GREAT work.

**Comment by jasonpang** [comment] 2016-08-26 23:01
Image proxy now changed to use Photon.

**Comment by jasonpang** [comment] 2016-09-28 01:09
Users haven't been reporting this issue recently in the last two weeks, so closing this issue. Will re-open another issue if it appears again.

**Comment by jasonpang** [comment] 2016-10-18 19:10
[This user](https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/6258548585) is reporting [their notification icon](https://onesignal.com/apps/5dc1b55f-5ad0-43d4-9c82-df083641a809/notifications/dd5d8f09-b948-4d81-b311-5d08d57605e1) did not appear when using an HTTP link.

**Comment by jasonpang** [comment] 2018-02-09 22:35
Not currently able to reproduce this, so closing the issue. Sending a `chrome_web_icon` through the API with an `http://` URL is displayed for me because it's converted to an `https://` image.

One thing to check for, if users aren't seeing the image, is a `Content-Security-Policy` header on the response to the service worker script. If it exists, it probably isn't allowing the image caching service request.

**Closed by jasonpang** 2018-02-09 22:35 UTC
Labels: needs: validation, type: bug
