### ISSUE TITLE
Firefox IndexedDb InvalidStateError - Print typed descriptive error

### ISSUE THREAD

**Issue by bjko** [OneSignal/OneSignal-Website-SDK#47] opened 2016-05-02 13:50 UTC
with Firefox 45 we on some workstations with windows (7, 8.1, 10) we are not able to use website push notifications. while using chrome browser this works on the same workstation.

we debugged the error in firebug:
Unable to open IndexedDB. error 
OneSignalSDK.js (Zeile 5)
UnknownError
OneSignalSDK.js (Zeile 5, Spalte 15054)

**Comment by jasonpang** [comment] 2016-05-03 01:18
Hi there,

It sounds like either you're using Firefox's Private Browsing Mode, or you're a victim of this error: https://bugzilla.mozilla.org/show_bug.cgi?id=1236557

If you're using Firefox's Private Browsing Mode, please use the normal Firefox browsing mode to test push notifications. If you're affected by the Bugzilla issue, you'll have to create a new Firefox profile following these instructions: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles. Once you've created a new Firefox profile, only use that profile in that version of Firefox (don't switch between Firefox versions with the same profile).

**Comment by bjko** [comment] 2016-05-03 09:19
Hi,
no we are not using the private browsing mode. We are affected by the Firefox bug. Deleting the old profile an creating a new one does fix it.
But how to deal with our customers, on our dev workstations we are able to deal with tthe profiles, but we are not able to fix this at our website customers. Any hints? Thanks

**Comment by jasonpang** [comment] 2016-05-04 23:11
Hi,

It's likely that your InvalidStateError is caused by using the same profile in different versions of Firefox, since you guys are all developing software and testing on different browsers. I don't think your customers will run into this specific error often. I can't imagine many users installing Firefox Beta or Firefox Nightly and switching between that and Firefox Stable.

**Comment by franklinjavier** [comment] 2016-10-21 13:28
@jasonpang May resolve with a try/catch
https://github.com/OneSignal/OneSignal-Website-SDK/blob/25e5e17eb437833e5c07bc43f4d5f372d064233c/src/indexedDb.js#L20

**Comment by jasonpang** [comment] 2016-11-29 02:12
Hey @franklinjavier,

I think it's a good idea to throw a more descriptive strongly typed error here from our SDK, so that the error can be more descriptively categorized. The error could even contain a link to the bug thread and other helpful information.

Unfortunately, we're not able to fix the core issue, which is that [the IndexedDb database, once used in a newer Firefox version, can no longer be used in older Firefox versions](https://bugzilla.mozilla.org/show_bug.cgi?id=1236557#c6). Although we can throw a more descriptive and friendly error, we can't open the IndexedDb database even if we catch the error.

Our SDK depends on IndexedDb for most of what it does, so if we run into this error, we're not able to really do anything about it unfortunately.

**Comment by jasonpang** [comment] 2016-12-10 00:08
Don't throw an error since users can't do anything about this (and it will use up their error reporting quota if they use such a service). Print a console warning or error though.

**Comment by PikachuEXE** [comment] 2017-01-09 02:12
Any update on this?
Still seeing the error this week

**Comment by jasonpang** [comment] 2017-01-10 21:24
Hey guys,

@PikachuEXE Can you paste the details of which error you're seeing? What specific message is your error reporter capturing?

This is very strange, and I'm open to any ideas, but I can't seem to be able to swallow this profile schema too high error. Here's the commit where the issue was attempted to be fixed, and this code is currently on `master` as well:

[Commit 5ba610d: IndexedDb.ts](https://github.com/OneSignal/OneSignal-Website-SDK/blob/5ba610d7146e929ba08bfdeea63fa2e7c14bb2d3/src/IndexedDb.ts)

This doesn't work:

```js
try {
    var request = indexedDB.open("ONE_SIGNAL_SDK_DB", 1);
} catch (e) {
    // Errors should be thrown on the request.onerror event, but 
    // just in case Firefox throws additional errors for profile schema too high
}
```

According to [the MDN docs on indexedDb.open()](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/open), the error should be thrown here:

```js
request.onerror = (event) => {
    const error = ( < any > event.target).error;
    if (contains(error.message, 'The operation failed for reasons unrelated to the database itself and not covered by any other error code')) {
        log.warn("OneSignal: IndexedDb web storage is not available on this origin since this profile's IndexedDb schema has been upgraded in a newer version of Firefox. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1236557#c6");
        // Never reject the Promise
    } else {
        log.error('OneSignal: Unable to open IndexedDB.', error.name + ': ' + error.message);
        reject(event);
    }
};
```

If your error reporters are capturing:

```
OneSignal: Unable to open IndexedDB. ..etc.
```

- This should be coming from the [`log.error`](https://github.com/OneSignal/OneSignal-Website-SDK/blob/5ba610d7146e929ba08bfdeea63fa2e7c14bb2d3/src/IndexedDb.ts#L44) call
- **Please paste the _full_ error name and message you're getting**
- We should add another `if` case to capture this

If your error reporters are capturing another error:

- I don't understand how this could be thrown since there is a [`try {} catch {}`](https://github.com/OneSignal/OneSignal-Website-SDK/blob/5ba610d7146e929ba08bfdeea63fa2e7c14bb2d3/src/IndexedDb.ts#L22) in the [`indexedDb.open()`](https://github.com/OneSignal/OneSignal-Website-SDK/blob/5ba610d7146e929ba08bfdeea63fa2e7c14bb2d3/src/IndexedDb.ts#L23) call, and you didn't get the "Unable to open IndexedDB" error in `request.onerror`, which is the [only code path that throws an error](https://github.com/OneSignal/OneSignal-Website-SDK/blob/5ba610d7146e929ba08bfdeea63fa2e7c14bb2d3/src/IndexedDb.ts#L43)
- **Please paste the _full_ error name and message you're getting**

<hr>

I'm getting:

![image](https://cloud.githubusercontent.com/assets/1015970/21825313/12f00672-d738-11e6-9fd3-80cd6944a861.png)

^ Clicking the error source opens:

![image](https://cloud.githubusercontent.com/assets/1015970/21825326/22c1f902-d738-11e6-9b0f-511cea419676.png)

<hr>

So it looks like the error is being thrown despite the `try {} catch {}` block.

**Comment by PikachuEXE** [comment] 2017-01-11 02:32
Here is the details of one error report for this error type

### User env

browser
Firefox 50.0
browser.name
Firefox
os.name
Windows 10
(These are displayed in Sentry, I have no idea what are the original values)

### Backtrace
```
./src/IndexedDb.ts in indexedDB at line 23:24
    return new Promise(function (resolve, reject) {
      if (IndexedDb._instance) {
        resolve(IndexedDb._instance);
      } else {
        try {
          var request = indexedDB.open("ONE_SIGNAL_SDK_DB", 1);
        } catch (e) {
          // Errors should be thrown on the request.onerror event, but just in case Firefox throws additional errors
          // for profile schema too high
        }
        request.onsuccess = ({target}) => {

```

### "Breadcrumb"
```
console
OneSignal: Unable to open IndexedDB. InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
10:23:55

exception
InvalidStateError
```

**Comment by jasonpang** [comment] 2017-01-11 03:03
Hey @PikachuEXE,

We'll add another if condition to swallow "A mutation operation was attempted on a database that did not allow mutations" and show a non-error "profile schema too high" warning. A different warning is displayed for me on Mac OS X, so maybe the error messages are different by OS.

**Comment by franklinjavier** [comment] 2017-01-20 01:26
Same here 

![image](https://cloud.githubusercontent.com/assets/440220/22132044/ae0f95ba-de9e-11e6-9fea-59a23b6e5385.png)

**Comment by jasonpang** [comment] 2017-01-20 01:30
Attempted fix will go out in next SDK release, but I don't think it will work since this seems like a Firefox bug.

I've reported the issue here, let me know if you guys think I'm missing anything or have an explanation for why the error can't be caught!

**Bug Report:** https://bugzilla.mozilla.org/show_bug.cgi?id=1331103

**Comment by franklinjavier** [comment] 2017-01-20 01:46
@jasonpang thanks for the support. I will still thinking in some workaround.

**Comment by PikachuEXE** [comment] 2017-01-20 01:47
@franklinjavier 
Let us know if you got a workaround
Thanks!

**Comment by jasonpang** [comment] 2017-02-22 04:10
Bevis Tseng from Mozilla suggested using `event.preventDefault()` (https://bugzilla.mozilla.org/show_bug.cgi?id=1331103#c3). This change will be live soon (https://github.com/OneSignal/OneSignal-Website-SDK/commit/c21c044e1a64af97136f28698b0f9029786a6b13).

**Comment by jasonpang** [comment] 2018-02-09 20:01
Closing this issue because I've confirmed the profile upgrade error is caught and replaced with a silent console message:

![image](https://user-images.githubusercontent.com/1015970/36047371-bd8353f2-0d90-11e8-808d-77b7d51cc550.png)

To reproduce:

1. Download any Firefox version >= 55, and subscribe to web push on that site w/ OneSignal.
2. Download any Firefox version < 55, and visit that site.
3. Observe the expected error message.

Not every version of Firefox is incompatible with older versions. For example, I was able to use Firefox 58 on a site after having already subscribed to web push on that site in Firefox 60. Firefox 55 happened to upgrade the Quota Manager according to a bug thread, so that's why there was a non-backwards compatible change.

**Closed by jasonpang** 2018-02-09 20:01 UTC
Labels: needs: validation, type: bug
