### ISSUE TITLE
how to get onesignal working with reactJS (not react native)?

### ISSUE THREAD

**Issue by Kliaqat** [OneSignal/OneSignal-Website-SDK#534] opened 2019-08-03 12:03 UTC
I am using oneSignal in react JS. All help I found so far is to add oneSignal configuration in index.html file which means that as soon as user will visit website, it will ask for notification Permission but our react JS application includes user login which means that user should only able to subscribe once he is login. 
So I have to add oneSignal configuration in react component. I came across react-helmet module of react for head things. 
`
import { Helmet } from 'react-helmet'
return (
      <JssProvider generateClassName={generateClassName}>
        <div className="main-container">
          <Helmet>
            var OneSignal = window.OneSignal || [];
            OneSignal.push(function() {
            OneSignal.init({
              appId: "xxxxxxx-xxx-xxxxx-xxxx-xxxxxxxxx",
              autoRegister: true,
              notifyButton: {
                enable: true,
              },
            });
            OneSignal.registerForPushNotifications();
          });
            OneSignal.push(function() {
            OneSignal.getUserId(function(userId) {
              console.log('player_id of the subscribed user is : ' + userId);
            });
          });
          </Helmet>
   </div>
      </JssProvider>
    `
and I get following error 
**Parsing error: Unexpected token, expected "}"**
at this semicolon 
`  notifyButton: {
                enable: true,
              },
            });`
P.S: I only posted relevant code

**Comment by rgomezp** [comment] 2019-08-05 19:04
Duplicate of https://stackoverflow.com/questions/57284394/issue-of-onesignal-integration-in-reactjs-application/57300470

**Closed by rgomezp** 2019-08-05 19:04 UTC
