### ISSUE TITLE
(#27670) A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by maximelafarie** [OneSignal/OneSignal-Website-SDK#286] opened 2017-11-20 13:28 UTC
I have an Angular project which use it. I have a OneSignal project for local dev (e.g.: localhost:4200), and another one for the production (e.g.: mywebsite.com).

I subscribed for the notifications on dev and all works well, but when I want to subscribe to the same notifications but in production environment, it fails with the errors mentioned above. And this is the same for all users who want to subscribe.

![image](https://user-images.githubusercontent.com/5319267/33020494-dc3f9868-cdfe-11e7-8d9f-2d6ebd65bc27.png)

Do I need to kill anything on my server ? Or is there a conflict between my SDKs ? (in dev vs prod)

Here is the content of my Chrome Application tab in the console:
![image](https://user-images.githubusercontent.com/5319267/33020533-0921c518-cdff-11e7-94b9-c6d0e525ce31.png)

**Comment by jasonpang** [comment] 2017-11-20 22:25
Hi there,

Could you reach out to us on support with your website URL so we can try to reproduce the issue? Or if you don't mind pasting it here you can do that too.

Some questions:

- If your production site is an HTTPS site, you should have uploaded a couple files (`manifest.json`, `OneSignalSDKWorker.js`, and `OneSignalSDKUpdaterWorker.js`) to your site. Can you try directly accessing either of the two JS files and see if you get the same 404 error?
- Does your server support case-sensitive URLs?
- Have you merged your own service worker into our service workers, and is your custom service worker calling `importScripts()` on a non-existent resource? If you've done this, you would have modified `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js` to add an `importScripts()` line above the existing line `importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js')`. If you haven't modified these files then don't worry about it.
- Are you using `https://cdn.onesignal.com/sdks/OneSignalSDK.js` for your OneSignal script?

**Comment by maximelafarie** [comment] 2017-11-21 17:53
Thank you for the quick answer @jasonpang!

No problem, my website is https://www.onmangeoucemidi.com/
Reproduce the issue is easy: you just need to click on the "bell" button : 
![image](https://user-images.githubusercontent.com/5319267/33088074-db3cf8a4-ceec-11e7-8ca4-c17e5f7a4d67.png)
to see the errors mentioned above in the browser's console.

My project use Angular 5 and I only import the `manifest.json` and `//cdn.onesignal.com/sdks/OneSignalSDK.js` like that:

```
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>My title</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="favicon.png" />
  <link rel="manifest" href="/assets/scripts/onesignal/manifest.json">

  <!-- OnesignalSDK script -->
  <script src="//cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
</head>
<body>
<app-root></app-root>
</body>
</html>
```

**Comment by mcsky** [comment] 2017-11-28 17:30
same issue here @jasonpang

**Comment by jasonpang** [comment] 2017-12-04 23:10
Hi @maximelafarie,

Sorry for the delay in getting back to you.

It looks like the OneSignalSDKWorker.js and OneSignalSDKUpdaterWorker.js files have been uploaded to `https://www.onmangeoucemidi.com/assets/scripts/onesignal/`. For most JavaScript files, this isn't ordinarily an issue because you'd just reference them wherever they are. Unfortunately, for JavaScript files that are later registered as background workers, where they are uploaded restricts what they can do. If possible, upload the files to the root directory of your site, otherwise you'll need the files to return an HTTP response header if they're in a subdirectory.

See https://documentation.onesignal.com/docs/web-push-sdk-setup-https#section-can-manifest-json-onesignalsdkworker-js-and-onesignalsdkupdaterworker-js-be-served-from-a-subfolder-of-my-site- for more details.

@mcsky Does that answer your question as well?

**Comment by jwilm** [comment] 2018-01-18 00:27
Please let us know if you're still having issues with this.

**Closed by jwilm** 2018-01-18 00:27 UTC

**Comment by jasonpang** [comment] 2018-03-26 17:15
Thanks for following up @gangsthub! One other DevTools-related service worker issue I noticed is in Chrome 65, using local overrides will also cause the service worker to not be loaded. In general, there are a couple DevTools related settings that can also cause service worker errors when the script is actually there. Testing on a new Chrome profile can ensure all extensions/settings are at their default values.
