### ISSUE TITLE
WrongSiteUrl error on localhost, with allowLocalhostAsSecureOrigin set to true

### ISSUE THREAD

**Issue by rossPatton** [OneSignal/OneSignal-Website-SDK#315] opened 2018-02-06 00:22 UTC
The full error:

```
reason: "WrongSiteUrl"
message: "OneSignal: This web push config can only be used on https://www.${myWebsite}.com. Your current origin is https://localhost:8443."
name: "SdkInitError"
stack: "SdkInitError: OneSignal: This web push config can only be used on https://www.${myWebsite}.com. Your current origin is https://localhost:8443
```

My init config:

```
OneSignal.push(function() {
  OneSignal.init({
    allowLocalhostAsSecureOrigin: true,
    appId: "${my-app-id-here}",
    autoRegister: false,
    notifyButton: {
      enable: true,
    },
  });
});
```

Basically, the initial config suggested by the dashboard, with `allowLocalhostAsSecureOrigin` set to true.

Can someone point out why this wouldn't work?

**Comment by rossPatton** [comment] 2018-02-06 02:04
Ok. So I changed the url in the dash to just be `https://localhost:8443`. I assume I will need to change this again later, but for now at least I've got some stuff working locally

I use webpack dev server in development, so I also had to check 'Bypass for network' in my chrome dev tools (under the applications tab, where service workers are managed). If I don't do this, I get the 'service worker is redundant' error, and dev server stops working. I basically had to unregister, check it, re-register, then uncheck again so dev server would work

So now I am at a point where the 2 onesignal SDK service workers are registered, and I have the logo in the bottom right (this can be disabled, right?). Clicking this gets me the ask prompt, but I never receive a notification, and no users show up in the dashboard

Confused about what the next step here should be

**Comment by jasonpang** [comment] 2018-02-06 21:39
Hey @rossPatton,

You can either change the URL or create a second test app when testing locally. If you're going to be testing with more than 100 users, settings like the Site URL won't be modifiable after the 101st user subscribes, so you'll need to create a second app in that case.

`allowLocalhostAsSecureOrigin` isn't needed in this case. It's used for treating `http://localhost` like `https://localhost` since Chrome treats `http://localhost` as a secure origin even despite the `http://`. Since your local development site is `https://`, this flag isn't needed.

**Comment by jasonpang** [comment] 2018-02-12 17:48
@rossPatton Going to close this issue for now, but if you reply I can open it back again and continue debugging where we left off. Or feel free to reach out to us at support@onesignal.com, it looks like this just might be a question and not a bug.

**Comment by eximius313** [comment] 2018-04-07 21:12
@jasonpang so what is the purpose of `allowLocalhostAsSecureOrigin` ?
I'd expect that if I put `https://myUrl` in the dashboard, and `allowLocalhostAsSecureOrigin` is false, then of course `"OneSignal: This web push config can only be used on https://www.${myWebsite}.com. Your current origin is https://localhost:8443."` error should appear BUT if `allowLocalhostAsSecureOrigin` is set to true, then BOTH `https://myUrl` and `localhost:8080` should work.

If I want to test this current app settings on localhost, I shoul not be forced to create new app (because I want to test *this particular app* settings)

**Comment by llwanghong** [comment] 2019-03-21 15:33
same issue, setting `allowLocalhostAsSecureOrigin: true` not working for Custom Code setup, it always complaining that 

> This web push config can only be used on https://my-setting.com. Your current origin is http://localhost:9191. 

Please help.

**Comment by llwanghong** [comment] 2019-03-21 16:00
After debugging the code, seems the setting `allowLocalhostAsSecureOrigin: true` is overwritten by config fetched from the code

```javascript
// Due to CloudFlare's algorithms, the .js extension is required for proper caching. Don't remove it!
                OneSignalApi.jsonpLib(`${SdkEnvironment.getOneSignalApiUrl().toString()}/sync/${appId}/web`, (err, data) => {
                    if (err)
                        reject(err);
                    else {
                        if (data.success)
                            resolve(data);
                        else // For JSONP, we return a 200 even for errors, there's a success: false param
                            reject(data);
                    }
                });
```
the fetched config including one `config.setupBehavior.allowLocalhostAsSecureOrigin` which is `false`, and finally my setting is overwritten by following code

```javascript
 const configIntegrationKind = this.getConfigIntegrationKind(serverConfig);
        const subdomain = this.getSubdomainForConfigIntegrationKind(configIntegrationKind, userConfig, serverConfig);
        const allowLocalhostAsSecureOrigin = (serverConfig.config.setupBehavior ?
            serverConfig.config.setupBehavior.allowLocalhostAsSecureOrigin :
            userConfig.allowLocalhostAsSecureOrigin);
```

@jasonpang

**Comment by eximius313** [comment] 2019-03-23 09:22
@jasonpang could you reopen the issue?

**Comment by llwanghong** [comment] 2019-03-29 07:55
seems @jasonpang left OneSignal, @rgomezp could you please help check the issue and reopen the issue?

**Comment by llwanghong** [comment] 2019-03-31 08:08
@fatsjohonimahnn could you please help check the issue and reopen it?

**Comment by rgomezp** [comment] 2019-04-01 23:20
Hello everyone,
It's used for treating http://localhost like https://localhost since Chrome treats http://localhost as a secure origin even despite the http://

If you have a main production site and also a local test site, please create a separate development app for testing locally.

Web push apps can only be used on the Site URL specified in your OneSignal dashboard. If you have an existing production app pointing to https://your-site.com, you can't simultaneously use this app on https://localhost. Additionally, apps with more than 100 users cannot change the Site URL, so you can't change your app's Site URL to point to https://localhost.

That's the gist. Check [here](https://documentation.onesignal.com/docs/web-push-setup-faq#section-how-do-i-test-my-site-on-a-local-environment-) for more info

The behavior you are describing is normal and you must create a separate app for each respective origin. The flag is simply for use between `http` and `https`.

**Comment by llwanghong** [comment] 2019-04-04 13:33
Well I try to understand the exact purpose of this `allowLocalhostAsSecureOrigin` setting. Is it right? @rgomezp 

> Generally, the `SITE URL` setting in OneSignal dashboard should be prefixed `https://`, otherwise we should additionally use the `CHOOSE A LABEL` setting. Since Chrome treats `http://localhost` as a secure origin, so OneSignal provides this `allowLocalhostAsSecureOrigin` setting to match this browser behavior, and only support the setting for these two URL exceptions `http://localhost` and `http://127.0.0.1`.

In addition, could you please give more explanation about my above debugging result, why my local `allowLocalhostAsSecureOrigin` setting will be overwritten by remote fetched `config.setupBehavior.allowLocalhostAsSecureOrigin` setting?

**Comment by rgomezp** [comment] 2019-04-08 20:43
@llwanghong 
The allowLocalhostAsSecureOrigin setting is for custom site integrations. Is this what you are using? If so, are you setting allowLocalhostAsSecureOrigin in your OneSignal init options? Are you seeing this value replaced to something other than the setting you configure?

**Comment by llwanghong** [comment] 2019-04-19 05:15
I further try the various settings, seems it is working well for me now. Thanks @rgomezp 
 
During `Configure Web Push`, step2 `Site Setup`, if `LOCAL TESTING` enabled, the remote fetched  `config.setupBehavior.allowLocalhostAsSecureOrigin`setting is true; otherwise the setting will be false.

**Comment by rgomezp** [comment] 2019-04-23 18:13
Great to hear @llwanghong ,
Will go ahead and close for now.

**Closed by rgomezp** 2019-04-23 18:13 UTC
Labels: domain: configuration, domain: service worker
