### ISSUE TITLE
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by Xaz16** [OneSignal/OneSignal-Website-SDK#716] opened 2020-11-02 08:13 UTC
**Description:**

I see that my error tracking system (Sentry) catch about 4.5k events from 673 users. I already seen closed https://github.com/OneSignal/OneSignal-Website-SDK/issues/503
But it is really hard to provide you more info about this issue. I can provide statistic about it, according to it I think you can find the root cause.
I have a project on angular 9 and use onesignal service worker in combine with angular service worker. As well I retrieving onesignalSDK from https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js

**Steps to Reproduce Issue:**

Stack trace:

```javascript
Unhandled Promise rejection: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. ; Zone: <root> ; Task: Promise.then ; Value: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at o (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:62634)
    at new x (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:15216)
    at c.<anonymous> (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:62604)
    at Generator.next (<anonymous>)
    at r (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:716)
    at u.invoke (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:7803)
    at a.run (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:3215)
    at https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:14147
    at u.invokeTask (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:8421)
    at a.runTask (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:3830)
    at m (https://www.mysite.coam/polyfills-es2015.b317dfadd8ad3527f616.js:1:10415)
    at l.invokeTask [as invoke] (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:9500)
    at h (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:21754)
    at d (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:22199)
extra: {"arguments":["Unhandled Promise rejection:","Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.","; Zone:","<root>","; Task:","Promise.then","; Value:",{"message":"Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.","name":"InvalidStateError","stack":"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\n    at o (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:62634)\n    at new x (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:15216)\n    at c.<anonymous> (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:62604)\n    at Generator.next (<anonymous>)\n    at r (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:716)\n    at u.invoke (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:7803)\n    at a.run (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:3215)\n    at https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:14147\n    at u.invokeTask (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:8421)\n    at a.runTask (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:3830)\n    at m (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:10415)\n    at l.invokeTask [as invoke] (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:9500)\n    at h (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:21754)\n    at d (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:22199)"},"Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.\n    at o (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:62634)\n    at new x (https://www.mysite.com/polyfills-es2015.b317dfadd8ad3527f616.js:1:15216)\n    at c.<anonymous> (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151104:1:62604)\n    at Generator.next (<anonymous>)\n    at r (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=1511..."]}
```

Statistic:
![image](https://user-images.githubusercontent.com/12300576/97844451-18e61400-1cfc-11eb-8600-cc57fb717abe.png)
![image](https://user-images.githubusercontent.com/12300576/97844490-30bd9800-1cfc-11eb-9cc7-b6f54415003d.png)

It looks like most of the time error can be reproduced in Windows 10

**Comment by jmadler** [comment] 2020-11-23 23:23
Closing as dupe of #503 which will be reopened.

**Closed** 2020-11-23 23:24 UTC
