### ISSUE TITLE
NotFoundError: IDBDatabase.transaction: 'Ids' is not a known object store name

### ISSUE THREAD

**Issue by Xaz16** [OneSignal/OneSignal-Website-SDK#671] opened 2020-07-15 12:50 UTC
**Description:**

I see in my error reporter a lots of issues which have in stacktrace your SDK, as example: 

```
put/</<@https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151002:1:63066
E@https://www.mysite.com/polyfills-es2015.a5891b23f2f57307ee0d.js:1:14302\
put/<@https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151002:1:63022
r@https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=151002:1:716
```

I have a PWA on latest Angular with OneSignalService worker and API script. 
As well I see lots of errors about trying to access the IDB. As example: https://github.com/OneSignal/OneSignal-Website-SDK/issues/503
Another:
InvalidStateError: IDBDatabase.transaction: Can't start a transaction on a closed database
NotFoundError: IDBDatabase.transaction: 'Options' is not a known object store name

**Anything else:**

As I can see it is often error on Firefox, and some of mobile browsers: Chrome Mobile, Samsung Internet

**Comment by jmadler** [comment] 2020-11-23 23:29
Closing as dupe of #503

**Closed by jmadler** 2020-11-23 23:29 UTC
