### ISSUE TITLE
Updating nested service worker (sw precache)

### ISSUE THREAD

**Issue by moklick** [OneSignal/OneSignal-Website-SDK#203] opened 2017-01-20 15:16 UTC
Hello,

we are using [sw-precache](https://github.com/GoogleChrome/sw-precache/) to cache our files in combination with the OneSignalWorker. As you explained in the docs we import our service worker in the OnesignalWorker. We are now facing the issue that we can't update cached files. We also found a related  [issue in the sw-precache repo](https://github.com/GoogleChrome/sw-precache/issues/169). Their solution is to use firebase. This is not really a solution for us, because we are using OneSignal in our iOS App and we are quite happy with it. Are you aware of this problem?

**Comment by jasonpang** [comment] 2017-01-21 02:23
Hey @moklick,

We weren't aware of this issue, sorry about the inconvenience it's causing. I'm still struggling to learn how sw-precache works. Can you explain in more detail why importing your script into our service worker, and allowing our SDK to register this merged (your SW + our SW) service worker causes issues with updating cached files?

**Comment by nolaandy** [comment] 2017-03-27 12:52
I'm having a similar issue I believe. Since my personal service worker caches files unique to that particular build, every time I build the site I need to build a new SW file with the new file names to my bundles. Therefore, in order for the site changes to be seen, the new service worker would have to be installed. By doing this though, the user would have to empty their cache to see site changes, the unfortunate outcome being that they are no longer subscribed to Push notifications and need to resubscribe.

**Comment by moklick** [comment] 2017-03-27 14:19
For now we are using the workaround that we add a hash to our service-worker script like:

**OneSignalSDKWorker.js**:
```
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
importScripts('/service-worker.B2Y-9zM2x.js');
```

**Comment by jasonpang** [comment] 2017-03-27 18:18
Hey @nolaandy,

Is the issue that changes in your own service worker file do not cause the your+OneSignal merged service worker to update on demand?

We update our service worker whenever the SDK we serve from our CDN at `https://cdn.onesignal.com/sdks/OneSignalSDK.js` updates with a new version. That SDK file contains both the code that subscribes users to push, and the code that is the service worker. Although, we only update our service worker whenever the SDK updates with a new version.

We call `navigator.serviceWorker.register(..)` with `OneSignalSDKWorker.js` or `OneSignalSDKUpdaterWorker.js`,  one or the other alternating to force the service worker to update when we need to.

I think it would be great to build out a better API for more control on updating service workers, but until then... First, you'll have to do something like [this comment](https://github.com/OneSignal/OneSignal-Website-SDK/issues/203#issuecomment-289467755).

^ Be sure to make those changes to _both_ `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js`.

Then I think some options are to:

a) Let the browser detect changes to `OneSignalSDKWorker.js` or `OneSignalSDKUpdaterWorker.js`, whichever happens to be installed as the active service worker. I believe this should happen within 24 hours, as long as the user visits your site or receives a push message (see: [When does Chrome update the service worker automatically?](https://bugs.chromium.org/p/chromium/issues/detail?id=674337#c2) ).

b) Kind of [copy what we do](https://github.com/OneSignal/OneSignal-Website-SDK/blob/ea851a49da41d82973a4970cbd8ccaf8bbaef15b/src/helpers/ServiceWorkerHelper.ts#L55) and, depending on which is installed, install the alternating `OneSignalSDKWorker.js` _or_ `OneSignalSDKUpdaterWorker.js`.

**Comment by jasonpang** [comment] 2018-02-12 23:48
I think the issue is being unable to update a custom service worker merged with OneSignal's service worker. Ordinarily, a site not using OneSignal and using only their own service worker could generate a new service worker with each build of their site, and have the service worker automatically update because Chrome checks whether the top-level script is different.

But when a site merges its own service worker with OneSignal, their custom service worker is no longer the top-level script, and the browser doesn't think the service worker has changed at all:

- Level 0 (registration): `navigator.serviceWorker.register('https://site.com/OneSignalSDKWorker.js');`

- Level 1 (`OneSignalSDKWorker.js`):
  ```
  // OneSignal's service worker
  importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');

  // Custom service worker
  importScripts('https://site.com/custom-service-worker.js');
  ```

- Level 2 (`custom-service-worker.js`):
  ```
   /* For users using sw-precache, the contents change on each build */
  self.addEventListener('install', function(event) {
    event.waitUntil(
      caches.open(cacheName).then(function(cache) {
        return cache.addAll(
          [
            '/css/bootstrap-sjyw3r23k.css',
            '/css/main-dygub2378ds.css',
            // ...
          ]
        );
      })
    );
  });

  self.addEventListener('activate', function(event) {
    /* Remove old cache */
  });
  ```

The issue is that changing the contents of `custom-service-worker.js` isn't seen by the browser as changing `OneSignalSDKWorker.js`, since only the top-level script (level 1) is checked for byte differences.

#### Solutions

- As @moklick suggested, changing anything in the top-level script will eventually cause the service worker to update. As long as a push event is received or a navigation is performed to a page controlled by the service worker after 24 hours since the last update check, another soft update check will be performed and the existing service worker will be updated.
  - You could change the URL with a dummy hash fragment `  importScripts('https://site.com/custom-service-worker.js#blah');` or a dummy query parameter `  importScripts('https://site.com/custom-service-worker.js?blah');` or a comment `  importScripts('https://site.com/custom-service-worker.js'); /* changed */`.
  - If you push out a large site update right after someone visits the site, I believe they won't see that update until they visit the site 24 hours later.

- Chrome might implement deep byte difference checking for all imported scripts

**Closed** 2018-02-12 23:49 UTC
Labels: difficulty: very time consuming, needs: discussion
