### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by junivillegas** [OneSignal/OneSignal-Website-SDK#278] opened 2017-11-03 17:13 UTC
![image](https://user-images.githubusercontent.com/3825784/32386776-f30a644e-c087-11e7-874f-e0716e7a6d32.png)

**Comment by natterstefan** [comment] 2017-11-16 10:50
@junivillegas I have two questions

- which command did you run in the console to get this error?
- Can you please change the title and make it more specific?

Thank you.

**Comment by jwilm** [comment] 2018-01-18 00:30
Duplicate of #298

**Closed by jwilm** 2018-01-18 00:30 UTC
