### ISSUE TITLE
[Bug]: Cannot use v11 login method -- "One or more Aliases claimed by another User"

### ISSUE THREAD

**Issue by bmulholland** [OneSignal/OneSignal-Website-SDK#1100] opened 2023-08-22 10:13 UTC
### What happened?

The SDK docs clearly say that login will create or find a user by that ID. Trying it the first time works, but after that the identify endpoint always returns an error "One or more Aliases claimed by another User"

### What browsers are you seeing the problem on?

Firefox, Chrome (Chromium)

### What operating system are you running?

latest macos

### Steps to reproduce?

```Markdown
OneSignal.login(externalid)

Logout

OneSignal.login(externalid)
```

### What did you expect to happen?

No error

**Comment by jkasten2** [comment] 2023-08-23 23:51
Thanks for reporting. I was able to reproduce the error showing in the JS console, but it does get handled correctly. The push subscription is transferred to the logged in User and future operations work correctly.

Here is the logging set to trace with `OneSignal.Debug.setLogLevel('trace');` with the full log.
```
OneSignalSDK.page.es6.js?v=160001:10533     PATCH https://onesignal.com/api/v1/apps/a3268fe7-cc94-4f25-ab09-867b957d7fe2/users/by/onesignal_id/9a2a831c-96b5-490f-b328-94118f56888b/identity 409
OneSignalSDK.page.es6.js?v=160001:6880 identifyUser failed: externalId already exists. Attempting to transfer push subscription...
OneSignalSDK.page.es6.js?v=160001:6886 transfer Subscription succeeded
```

We definitely shouldn't be showing that as an error though, as it is very misleading, so we will get that cleaned up in a future release.

**Comment by jkasten2** [comment] 2023-11-15 17:52
We have added the logging to point out the `409` is expected so this isn't a misleading message in our [160002 release](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/160002).

I am not able to reproduce an issue here, the subscription is transferring and confirmed it show correctly on the OneSignal dashboard.

**Closed by jkasten2** 2023-11-15 17:52 UTC
