### ISSUE TITLE
When run in privacy mode OneSignlal behaves differently in Chrome and Firefox

### ISSUE THREAD

**Issue by mike-shmatov** [OneSignal/OneSignal-Website-SDK#442] opened 2018-11-22 09:45 UTC
**Description:**

Relying on combination of `OneSignal.isPushNotificationsSupported()` and `OneSignal.isPushNotificationsEnabled()` will resolve to different scenarios. In Chrome `OneSignal.isPushNotificationsEnabled()` will resolve to `false`, and in Firefox it stays pending thus preventing further actions.

**Steps to Reproduce Issue:**

Chrome:
1. open Chrome in privacy mode 
2. visit https://onesignal.com/, btw note the subscription bell present in the bottom of the screen
3. Ctrl + Shift + I   and proceed to console
4. `OneSignal.isPushNotificationsSupported()  // true`
5. `OneSignal.isPushNotificationsEnabled().then(console.log) // false`

Firefox:
1. open Firefox in privacy mode 
2. visit https://onesignal.com/, note absence of subscription bell
3. Ctrl + Shift + I   and proceed to console
4. `OneSignal.isPushNotificationsSupported()  // true`
5. `OneSignal.isPushNotificationsEnabled().then(console.log) // will not resolve nor reject, always pending`

Performed in Chrome 68.0.3440.106 and Firefox 61.0.2

**Anything else:**

1. I met the issue after one of the clients complained about "why doest it keep prompting me to subscribe event after I already agreed > 10 times". I could never reproduce such behaviour untill opening site in Chrome with privacy mode on (I could not gain direct access to the actual browser instance he uses but I suspect it's either somehow configured to be privacy-mode-like or has some weird extensions installed). Anyway, if subscription is not really possible, prompting for it looks confusing.
2. Not really sure if this should be reported as a bug since this could be some sort of expected behaviour (or such cases might just be non-goals), and the developer is quite supposed to perform some extra care (although I can't really recall anything relevant in the docs).

**Comment by jkasten2** [comment] 2018-11-25 23:07
@mike-shmatov Thanks for all the details and the step-by-steps. I toke a quick look and it seems like on Firefox private mode `OneSignal.initialized` is never becoming `true`. This means there was an error or something blocking initialization. We will take a deeper look this week

**Comment by MaximusBaton** [comment] 2019-03-21 13:56
I'm facing the same issue even not in privacy mode.
The code was not changed and worked fine!
But today I noticed the same issue. isPushNotificationsEnabled is never resolved.

**Comment by MaximusBaton** [comment] 2019-03-21 14:22
btw, the notification bell is not shown on  https://onesignal.com/

**Comment by jkasten2** [comment] 2019-03-21 19:04
@MaximusBaton  Thanks for the details, I was only able to reproduce the issue with `isPushNotificationsEnabled()` not resolving in Firefox with a private window. What browser did you reproduce this issue on?

We removed the bell widget on our site since there is now a "See an Example" button on our main page.

**Comment by MaximusBaton** [comment] 2019-03-21 20:03
@jkasten2 , I'm on Windows 10x64, Google Chrome 72.0.3626.121
Here is the code sample I'm using:

```
$(document).ready(function () {

    var OneSignal = window.OneSignal || [];

    OneSignal.push(function() {
        OneSignal.init({
            appId         : "APP_ID",
            autoRegister  : true,
            welcomeNotification: {
                disable: true
            },
            promptOptions : {
                exampleNotificationTitleDesktop: "...",
                exampleNotificationTitleMobile: "...",
                exampleNotificationMessageDesktop: "Sample message",
                exampleNotificationMessageMobile: "Sample message",
                acceptButtonText: "ALLOW",
                cancelButtonText: "NO THANKS",
                showCredit: false
            },
            notifyButton: {
                enable          : true, /* Required to use the Subscription Bell */
                size            : 'medium', /* One of 'small', 'medium', or 'large' */
                offset          : {
                    bottom: '90px',
                },
                prenotify       : true, /* Show an icon with 1 unread message for first-time site visitors */
                showCredit      : false, /* Hide the OneSignal logo */
                colors          : { // Customize the colors of the main button and dialog popup button
                    'circle.background': '#991d85',
                    'circle.foreground': 'white',
                    'badge.background': '#991d85',
                    'badge.foreground': 'white',
                    'badge.bordercolor': 'white',
                    'pulse.color': 'white',
                    'dialog.button.background.hovering': '#991d85',
                    'dialog.button.background.active': '#991d85',
                    'dialog.button.background': '#991d85',
                    'dialog.button.foreground': 'white'
                },
                displayPredicate: function() {
// We go here on page load
                    return OneSignal.isPushNotificationsEnabled()
                        .then(function(isPushEnabled) {
// We never go here as this Promise is never resolved
                            /* The user is subscribed, so we want to return "false" to hide the Subscription Bell */
                            return !isPushEnabled;
                        });
                },
            }
        });
        
        // Occurs when the user's subscription changes to a new value.
        OneSignal.on('subscriptionChange', function (isSubscribed) {
            if (isSubscribed === true) {
                OneSignal.getUserId().then(function(userId) {
                    rememberUser(userId);
                });
            }
        });
    });
    
    function rememberUser(userId) {
        $.ajax({
            url   : 'some-url',
            type  : 'post',
            data  : {
                id    : userId
            },
            success: function(response) {
                // ...
            }
        });
    }
});

```

The same situation I have in FireFox 66.0.
Both, Chrome and FF, have this problem in normal and privacy mode.

What is the desired behavior:
- when a user accepts notifications, the bell never shown again
- when a user enters the page for the first time, the native notifications request appears - works fine
- when a user declined to receive notifications, the bell icon is shown and lets him to change his decision later - not working anymore because of `isPushNotificationsEnabled`

**Comment by MaximusBaton** [comment] 2019-03-29 16:09
I created a test page with example code (from [docs](https://documentation.onesignal.com/docs/bell-prompt#section-custom-code-setup-bell-customizations), `HTTPS Full Example Code`), and the notification bell is very unstable. It was shown couple of times, and not every time I reload the page. Pretty weird behavior.

**Comment by rgomezp** [comment] 2019-04-01 22:55
Hello @mike-shmatov @MaximusBaton , 
It would be extremely helpful to me if I could take a look at your respective sites. If you would like to engage in a private forum, please contact us through the support bubble at OneSignal.com and paste the URL to this thread.

**Comment by MaximusBaton** [comment] 2019-04-09 10:35
So. After talking with support (as @rgomezp advised) I finally managed to it to be working.
My code mentioned in this thread previously ([link](https://github.com/OneSignal/OneSignal-Website-SDK/issues/442#issuecomment-475381608)) has **no** changes.

The **most important thing** was to **place** the **code** into the **`<head>`** section, and not before ending `</body>` as it commonly being done.

**Closed** 2019-04-18 17:34 UTC
Labels: type: bug
