### ISSUE TITLE
Custom code : Fire setSubscription 

### ISSUE THREAD

**Issue by mvigneron** [OneSignal/OneSignal-Website-SDK#342] opened 2018-04-06 20:14 UTC
Hi,

I'm trying to develop a custom ui registration. 

I have a button "Subscribe to Notifications / Unsubscribe from Notifications". When I click on "Subscribe to Notifications", I would like to set subscription to true and change button to "Unsubscribe from Notifications". 
And so, When I click on "Unsubscribe from Notifications", I would like to set subscription to false and change button to "Subscribe to Notifications"

I saw the doc https://documentation.onesignal.com/docs/web-push-custom-code-examples#section-custom-link-prompt

Function setSubscription(true) fire event "subscriptionChange"(just once after refresh page) but setSubscription(false) doesn't fire event "subscriptionChange"

So, what is the best way to do that without refresh page ?

Example Code : 

```HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>WebPush example</title>
    <link rel="manifest" href="/manifest.json" />
	<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
	<script>

        function onManageWebPushSubscriptionButtonClicked(event) {
            getSubscriptionState().then(function(state) {
                if (state.isPushEnabled) {
                    /* Subscribed, opt them out */
                    OneSignal.setSubscription(false);
                } else {
                    if (state.isOptedOut) {
                        /* Opted out, opt them back in */
                        OneSignal.setSubscription(true);
                    } else {
                        /* Unsubscribed, subscribe them */
                        OneSignal.registerForPushNotifications();
                    }
                }
            });
            event.preventDefault();
        }

        function updateMangeWebPushSubscriptionButton(buttonSelector) {
            var hideWhenSubscribed = false;
            var subscribeText = "Subscribe to Notifications";
            var unsubscribeText = "Unsubscribe from Notifications";

            getSubscriptionState().then(function(state) {
                var buttonText = !state.isPushEnabled || state.isOptedOut ? subscribeText : unsubscribeText;

                var element = document.querySelector(buttonSelector);
                if (element === null) {
                    return;
                }

                element.removeEventListener('click', onManageWebPushSubscriptionButtonClicked);
                element.addEventListener('click', onManageWebPushSubscriptionButtonClicked);
                element.textContent = buttonText;

                if (state.hideWhenSubscribed && state.isPushEnabled) {
                    element.style.display = "none";
                } else {
                    element.style.display = "";
                }
            });
        }

        function getSubscriptionState() {
            return Promise.all([
                OneSignal.isPushNotificationsEnabled(),
                OneSignal.isOptedOut()
            ]).then(function(result) {
                var isPushEnabled = result[0];
                var isOptedOut = result[1];

                return {
                    isPushEnabled: isPushEnabled,
                    isOptedOut: isOptedOut
                };
            });
        }

        var OneSignal = OneSignal || [];
        OneSignal.push(["init", {
            appId: "APP_ID",
            autoRegister: false, /* Set to true to automatically prompt visitors */
            notifyButton: {
                enable: false, /* Required to use the Subscription Bell */
                /* SUBSCRIPTION BELL CUSTOMIZATIONS START HERE */
                size: 'large', /* One of 'small', 'medium', or 'large' */
                theme: 'default', /* One of 'default' (red-white) or 'inverse" (white-red) */
                position: 'bottom-right', /* Either 'bottom-left' or 'bottom-right' */
                offset: {
                    bottom: '15px',
                    left: '15px', /* Only applied if bottom-left */
                    right: '15px' /* Only applied if bottom-right */
                },
                prenotify: true, /* Show an icon with 1 unread message for first-time site visitors */
                showCredit: false, /* Hide the OneSignal logo */
                text: {
                    'tip.state.unsubscribed': 'Recevez les infos des commerces en temps réel',
                    'tip.state.subscribed': "Vous recevez les notifications",
                    'tip.state.blocked': "Vous avez bloqué l'envoi de notification",
                    'message.prenotify': 'Cool ! Vous ne raterez aucune info !',
                    'message.action.subscribed': "Vous recevez les notifications",
                    'message.action.resubscribed': "Cool ! Vous ne raterez aucune info !",
                    'message.action.unsubscribed': "Pas de souci ! Vous ne recevrez plus les infos des commerces",
                    'dialog.main.title': 'Gestion des Notifications',
                    'dialog.main.button.subscribe': 'Recevoir les notifications',
                    'dialog.main.button.unsubscribe': 'Ne plus recevoir les infos',
                    'dialog.blocked.title': 'Bloquer les notifications',
                    'dialog.blocked.message': "Suivez ces instructions pour réactiver les notifications"
                },
                colors: { // Customize the colors of the main button and dialog popup button
                    'circle.background': 'rgb(228,141,23)',
                    'circle.foreground': 'black',
                    'badge.background': 'rgb(228,141,23)',
                    'badge.foreground': 'black',
                    'badge.bordercolor': 'black',
                    'pulse.color': 'black',
                    'dialog.button.background.hovering': 'rgb(77, 101, 113)',
                    'dialog.button.background.active': 'rgb(70, 92, 103)',
                    'dialog.button.background': 'rgb(84,110,123)',
                    'dialog.button.foreground': 'white'
                }

                /* HIDE SUBSCRIPTION BELL WHEN USER SUBSCRIBED */
                /*displayPredicate: function() {
                    return OneSignal.isPushNotificationsEnabled()
                        .then(function(isPushEnabled) {
                            return !isPushEnabled;
                        });
                }*/
            },
            /* Prompt option */
            promptOptions: {
                /* actionMessage limited to 90 characters */
                actionMessage: "Vous voulez recevoir les infos/promotions des commerces en temps réel ?",
                /* acceptButtonText limited to 15 characters */
                acceptButtonText: "Oui !",
                /* cancelButtonText limited to 15 characters */
                cancelButtonText: "Non Merci"
            },
            /* Your other init options here */
            welcomeNotification: {
                "title": "OneSpot - Notification",
                "message": "Merci ! Vous ne raterez aucune info des commerces. Vous pouvez filtrer les notifs dans votre espace perso",
                // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
            }
        }]);
        var buttonSelector = "#my-notification-button";

        /* This example assumes you've already initialized OneSignal */
        OneSignal.push(function() {
            // If we're on an unsupported browser, do nothing
            if (!OneSignal.isPushNotificationsSupported()) {
                return;
            }
            updateMangeWebPushSubscriptionButton(buttonSelector);
            OneSignal.on("subscriptionChange", function(isSubscribed) {
                /* If the user's subscription state changes during the page's session, update the button text */
                console.log('subscriptionchange :' ,isSubscribed);
                updateMangeWebPushSubscriptionButton(buttonSelector);
            });
            OneSignal.on('notificationPermissionChange', function(permissionChange) {
                var currentPermission = permissionChange.to;
                console.log('New permission state:', currentPermission);
            });
        });
	</script>
</head>
<body>
    <h1>WebPush notification</h1>
    <ul>
        <li><a href="#" id="my-notification-button" style="display: none;">Subscribe to Notifications</a></li>
    </ul>
</body>
</html>
```

Thanks

**Comment by jkasten2** [comment] 2018-04-23 21:10
@mvigneron The [`subscriptionChange`](https://documentation.onesignal.com/docs/web-push-sdk#section-subscription-change) event does not fire for `setSubscription` changes. This currently excluded.

To update the button without a page refresh you will need to call `updateMangeWebPushSubscriptionButton` from  `onManageWebPushSubscriptionButtonClicked`.
```javascript
function onManageWebPushSubscriptionButtonClicked(event) {
  getSubscriptionState().then(function(state) {
    if (state.isPushEnabled) {
      /* Subscribed, opt them out */
      OneSignal.setSubscription(false);
    } else {
      if (state.isOptedOut) {
        /* Opted out, opt them back in */
        OneSignal.setSubscription(true);
      } else {
        /* Unsubscribed, subscribe them */
        OneSignal.registerForPushNotifications();
      }
    }
    // HERE: Line added
    updateMangeWebPushSubscriptionButton("#my-notification-button");
  });
  event.preventDefault();
}
```

**Comment by AcidRaZor** [comment] 2018-06-05 13:33
@jkasten2 Why would the example show registering a hook in 'subscriptionChange' and that working for when someone subscribes, but according to you, it doesn't work at all and shouldn't be used? subscriptionChange being fired when subscribing AND unsubscribing should work, not just one or the other.

Either update your documentation or clarify it so that others (including myself) don't spend a few hours trying to figure out why the unsubscribe event never fires (btw, if you have the subscription bell on the same page, it fires fine)

I would label this as a bug for further investigation

**Comment by AcidRaZor** [comment] 2018-06-05 14:18
@mvigneron I played around with this and it seems the rate at which setSubscription fires might be the root cause somehow. Replace your function onManageWebPushSubscriptionButtonClicked. You will notice I use "then" on setSubscription to wait for the response before attempting a button change;

```
function onManageWebPushSubscriptionButtonClicked(event) {
            getSubscriptionState().then(function(state) {
                if (state.isPushEnabled) {
                    OneSignal.setSubscription(false).then(function (){
                          updateMangeWebPushSubscriptionButton(buttonSelector);
                    });
                } else {
                    if (state.isOptedOut) {
                        OneSignal.setSubscription(true).then(function (){
                          updateMangeWebPushSubscriptionButton(buttonSelector);
                        });
                    } else {
                        OneSignal.registerForPushNotifications();
                    }
                }
            });
            event.preventDefault();
        }
```

**Comment by mvigneron** [comment] 2018-06-13 08:15
thanks @AcidRaZor 

I will testing that ;-)

**Comment by jkasten2** [comment] 2018-08-07 00:36
@AcidRaZor @mvigneron I tested `subscriptionChange` with `setSubscription` again on the latest `150402` SDK version and was no longer able to reproduce an issue. Each time I call `setSubscription` that results in a change `subscriptionChange` fires. Note that the call to `subscriptionChange` may take a second or 2 as this waits for a reply from OneSignal's API to make sure the value did change.

**Comment by itrush** [comment] 2018-08-16 17:32
Closing this issue. Please open a new one if you figure out the specific steps to reproduce. Thanks.

**Closed by itrush** 2018-08-16 17:32 UTC
Labels: type: question
