### ISSUE TITLE
Site configuration setup help

### ISSUE THREAD

**Issue by rishab-yumist** [OneSignal/OneSignal-Website-SDK#94] opened 2016-07-12 13:01 UTC
Hey,

I'm trying to configure web pushes. 

I added an https url, but the push doesn't work with it. 

![screen shot 2016-07-12 at 6 29 06 pm](https://cloud.githubusercontent.com/assets/13828707/16767800/b2701ae8-485e-11e6-9014-0626e8e40929.png)

Secondly, if I tried to change to http, it works but nothing happens when I click on the allow button in the popup.
![Uploading Screen Shot 2016-07-12 at 6.31.51 PM.png…]()

Could you help me with it?

**Comment by jasonpang** [comment] 2016-07-12 18:06
Hello @rishab-yumist,

Looks like you integrated our web SDK into your site successfully, however there are still some issues:
- If you check your OneSignal dashboard, you'll get a configuration error because the Google Server API Key you entered isn't valid. The key you've entered looks pretty long ... give it another check! 
- Your webpage is calling `OneSignal.sendSelfNotification()` when OneSignal isn't loaded yet. Because our script is loaded asynchronously, you'll have to wrap that inside a `OneSignal.push(function() { ... });` block.

**Comment by rishab-yumist** [comment] 2016-07-13 05:21
Hello @jasonpang 

I updated the google key. I removed the onesignal.sendSelfNotifcation() code and tried subscribing to the notifications. The user doesn't show up in the users dashboard in onesignal, also nothing happens when I click on allow in the notification for subscription.

`<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
    <script>
    var OneSignal = OneSignal || [];
       OneSignal.push(["init", {
         appId: "34888198-5f3e-4fe1-9034-81c20536ffc1",
         autoRegister: true,
         notifyButton: {
           enable: true /* Set to false to hide */
         }
       }]);
    </script>`

**Comment by jasonpang** [comment] 2016-07-13 05:36
Hi @rishab-yumist,

Looks like https://www.yumdev.com/OneSignalSDKWorker.js is returning a 404 not found? Did you remove the file (it was there yesterday). That file needs to be there for notifications to work (see step 2 of our HTTPS web push setup guide for the other files that need to be present: https://documentation.onesignal.com/docs/website-sdk-installation#2-upload-required-files).

**Comment by rishab-yumist** [comment] 2016-07-13 05:50
Hey @jasonpang 

I got the https://www.yumdev.com/OneSignalSDKWorker.js  working. But nothing happens when I try to click on the red notification button for subscribing. Could you have a look at yumdev.com?

**Comment by jasonpang** [comment] 2016-07-13 06:54
Hey @rishab-yumist,

Looks like you got it working? :) I see your welcome notification, which means everything works now.

**Comment by rishab-yumist** [comment] 2016-07-13 06:55
@jasonpang I can't see the welcome notification. Where did you see it?

**Comment by jasonpang** [comment] 2016-07-13 06:56
Are you successfully subscribed? If so, click the red notify button on the bottom right corner of your page to click "Unsubscribe". Wait 2.5 seconds, and then click "Subscribe" again. You should see a welcome notification on your screen,

Make sure you're not using Chrome in full-screen mode, as this hides notifications.

**Comment by rishab-yumist** [comment] 2016-07-13 07:01
I clicked on the subscribe button, nothing happened. When I hover over the button I see this (attached picture)

![screen shot 2016-07-13 at 12 30 43 pm](https://cloud.githubusercontent.com/assets/13828707/16794496/acc4a414-48f5-11e6-97ab-40083a6dc4f1.png)

I clicked on it and waited, nothing happened. I exited the full screen mode too. 

Did you try to see the welcome notification on http://www.yumdev.com ?

**Comment by jasonpang** [comment] 2016-07-13 07:07
Hi @rishab-yumist,

Could you follow this guide and send us the web SDK debug log? https://documentation.onesignal.com/docs/guides-examples#viewing-web-sdk-debug-logs

**Comment by jasonpang** [comment] 2016-07-13 07:10
Got your test chrome push.

**Comment by rishab-yumist** [comment] 2016-07-13 07:12
@jasonpang I guess there's some issue with my browser. I tried on my phone, it's working. Weird. let me try to send your the debug logs.

**Comment by rishab-yumist** [comment] 2016-07-13 07:30
I added logs @jasonpang 

Attaching images. 

![screen shot 2016-07-13 at 12 59 20 pm](https://cloud.githubusercontent.com/assets/13828707/16795212/b173ad58-48f9-11e6-8345-c3bf44730f93.png)
![screen shot 2016-07-13 at 12 59 25 pm](https://cloud.githubusercontent.com/assets/13828707/16795213/b175d4d4-48f9-11e6-9f49-f7c5aa7cad8c.png)
![screen shot 2016-07-13 at 12 59 32 pm](https://cloud.githubusercontent.com/assets/13828707/16795214/b17be504-48f9-11e6-8a81-178f95b1c09a.png)


This isn't specifically working for a few chrome browsers. What may be the issue? Although all of these browsers have the updated versions.

**Comment by jasonpang** [comment] 2016-07-13 07:36
Hey @rishab-yumist,

For the [second screenshot](https://cloud.githubusercontent.com/assets/13828707/16795213/b175d4d4-48f9-11e6-9f49-f7c5aa7cad8c.png), do you have the log of what happens after that? The text contents are cut off and the last screenshot you posted isn't the continuation of the second screenshot. The rest of the second screenshot should be helpful in diagnosing what happened to the subscription attempt. Second screenshot looks pretty good so far. First screenshot is just setup so isn't too useful.

**Comment by rishab-yumist** [comment] 2016-07-13 07:40
Hey @jasonpang 

Attaching just the logs. 

![screen shot 2016-07-13 at 1 09 42 pm](https://cloud.githubusercontent.com/assets/13828707/16795481/289571f4-48fb-11e6-9e16-f5c3225fd6f4.png)

After clicking the subscribe button: 

![screen shot 2016-07-13 at 1 10 31 pm](https://cloud.githubusercontent.com/assets/13828707/16795499/391487b8-48fb-11e6-883c-e9ab6705da6b.png)

**Comment by jasonpang** [comment] 2016-07-13 07:46
Hey @rishab-yumist,

So sorry, I provided faulty instructions the first time around. It looks like the notification permission prompt is already being displayed, and so clicking the red notify button will not do anything, because the permission prompt is already being displayed (and all the red notify button does is also display the same permission prompt).

Could you please click Allow (make sure you're allowing _notification_ permissions, since you also ask the user for location permissions), and paste the log output for what happens once you click Allow? That will subscribe you.

**Comment by rishab-yumist** [comment] 2016-07-13 07:47
@jasonpang I can't see the permission notification at all. Also, I have allowed the notifications for the site. Do you want me to change the notification permissions and retry?

**Comment by rishab-yumist** [comment] 2016-07-13 07:52
@jasonpang I changed the notifications settings to always 'ask' and then I clicked on the allow notifications permission. After that I tried clicking on the subscribe button, but still nothing happened.

**Comment by jasonpang** [comment] 2016-07-13 07:53
Hey @rishab-yumist,

This is very strange. Would you like to do a quick TeamViewer session right now? You can click the red support button on onesignal.com and send us your TeamViewer ID and password.

**Comment by rishab-yumist** [comment] 2016-07-13 07:55
@jasonpang Alright. Give me 5.

**Comment by jasonpang** [comment] 2016-07-13 18:39
rishab-yumist had what appears to be a profile bug in Chrome where the call to `pushManager.subscribe()` was hanging and the Promise was not resolving (on multiple sites we tested). Creating a new Google Chrome profile resolved the issue. He had a similar issue in Safari where clearing Safari's website data resolved the issue (Safari -> Preferences -> Privacy -> Clear Website Data).

**Closed by jasonpang** 2016-07-13 18:39 UTC

**Comment by kirarpit** [comment] 2016-09-06 10:25
@jasonpang, i'm using Chrome 53 and the same thing happened. Creating another user resolved the issue though but any insights on how can this case be handled? Thanks.

**Comment by jasonpang** [comment] 2016-09-07 20:17
Hey @kirarpit,

I'm pretty sure this is a Chrome-specific issue, and another user opened a bug thread about this here (https://bugs.chromium.org/p/chromium/issues/detail?id=623062). Based on the issues people ask us for help with, I'd say this issue is very rare; I've ran into it twice in half a year and we've only ever got around three or four support requests for it. I don't know of any steps to reproduce the issue, but I did dig around and delete specific files in my Chrome user profile that sounded like it was related to service workers/google cloud messaging and I didn't have to delete my profile:

e.g. `/Users/jpang/Library/Application Support/Google/Chrome`
`mv "GCM Store" "GCM Store Backup"`

^ actually fixes the issue.

I'm afraid there's nothing code-wise that can be done.

**Comment by kovalevski** [comment] 2016-09-28 08:25
Hi @jasonpang,

yesterday I faced the same issue and your solution fixed the problem. In my Chrome v.53 the folder was `/Users/[user-name]/Library/Application Support/Google/Chrome/Default/GCM Store`

**Comment by jasonpang** [comment] 2016-09-29 19:30
Hey @kovalevski,

Thanks for the corrected path. I had to run this command again this morning, and it was the `Default` folder that worked. 

(Note to self / general bug logging): I ran into a strange issue where, I was debugging the service worker push event by simulating a push event, by clicking Push at the top right:
![image](https://cloud.githubusercontent.com/assets/1015970/18969030/4b128cd0-8640-11e6-937d-3819130b7ecc.png)

After clicking the Push link many times (maybe 15+ times) really fast, I wasn't able to see the notification displayed anymore. Based on the service worker logging, I could see that my notification was being "displayed", but the notification itself wasn't visible.
