### ISSUE TITLE
OneSignal.database.getSubscription throws error

### ISSUE THREAD

**Issue by nomocas** [OneSignal/OneSignal-Website-SDK#835] opened 2021-06-21 15:57 UTC
**Description:**

Something throws after some time after initialisation (init is ok)

MainHelper.js:188 Uncaught (in promise) TypeError: Cannot read property 'getSubscription' of undefined
    at Function.<anonymous> (MainHelper.js:188)
    at Generator.next (<anonymous>)
    at tslib.es6.js:65
    at new Promise (<anonymous>)
    at n (tslib.es6.js:61)
    at Function.getDeviceId (MainHelper.js:187)
    at hi.<anonymous> (SessionManager.js:151)
    at Generator.next (<anonymous>)
    at tslib.es6.js:65
    at new Promise (<anonymous>)
    at n (tslib.es6.js:61)
    at hi.handleOnBlur (SessionManager.js:140)
  ...

MainHelper.js is trying to call getSubscription through a "database" var which should belong to OneSignal object.

line 188: `const subscription = await OneSignal.database.getSubscription();`

After search in the github repo : there is nowhere else any traces of such var.
I really believe that it should be "await Database.getSubscription();" (as all other call to internal Database client)

The throw appeared after introduction of OneSignal.isPushNotificationsEnabled (see below my init function).

In the typescript sources, the problematic line is at helpers/MainHelper.ts line 214 :
```typescript
  static async getDeviceId(): Promise<string | undefined> {
    const subscription = await OneSignal.database.getSubscription();
    return subscription.deviceId || undefined;
  }
```

**Steps to Reproduce Issue:**

1. just start an app
2. initialise OneSignal as documentation describes (everything is loaded directly from CDN) with OneSignal.isPushNotificationsEnabled
3. Wait a little bit (sometime 15 seconds, sometime 60)
4. boom : something throw

**Anything else:**

My init function :

```typescript
const init = () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const OneSignal = (window as any).OneSignal;
    OneSignal.init({
        appId: process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID as string,
        autoResubscribe: true,
        notifyButton: {
            enable: true,
        },
        allowLocalhostAsSecureOrigin: true,
        promptOptions: {
            slidedown: {
                enabled: true,
                autoPrompt: true,
                timeDelay: 5,
                //   pageViews: 3
            },
        },
        welcomeNotification: {
            title: 'Welcome!',
            message: 'Cheers...',
            // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
        },
        persistNotification: false, // Automatically dismiss the notification after ~20 seconds in non-mobile Chrome
    });

    OneSignal.isPushNotificationsEnabled((isEnabled: boolean) => {
        if (isEnabled) {
            console.log('Push notifications are enabled!');
            OneSignal.getUserId((userId: string) => {
                // Make a POST call to your server with the user ID
                console.log('Push Notifications userid (%s)', userId);
            });
        } else {
            console.log('Push notifications are not enabled yet.');
        }
    });
};

export default init;
```

By the way, the OneSignal.isPushNotificationsEnabled is working (at init time)

**Edit : **

Here is the blame...

https://github.com/OneSignal/OneSignal-Website-SDK/commit/a8fee9c33f17371c2d11005d8366e4cfd96a52cf

What is really strange, is that this commit has been done on 8 April 2020... more than a year...
Am I the only one having this issue ?

**Comment by emawby** [comment] 2021-08-10 16:49
@nomocas I apologize that this is not working as expected, however I am not able to reproduce this issue. [OneSignal.database is defined here](https://github.com/OneSignal/OneSignal-Website-SDK/blob/48516f8c1896766a74e0286dd6ef960316dfdb1b/src/OneSignal.ts#L870), and should reference the same static class as calling `Database` directly.

Can you provide more context about where this code is being executed from, and do you have a public website with this issue?

**Comment by emawby** [comment] 2021-08-24 19:46
@nomocas Closing this issue, but if you are still experiencing this problem please reopen

**Closed by emawby** 2021-08-24 19:46 UTC
Labels: Need More Information
